# Generated by Django 4.0 on 2021-12-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_alter_studentdetails_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
